fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Entity\Usuario
  from_email:
    address: "sistema@prof.com"
    sender_name: "Sistema"